### PR TITLE
Stylelint

### PR DESCRIPTION
**Pull request by unamaria**

### CODE REVIEW

**Comment by unamaria** [comment]
Adds `sass-lint` gulp task. There are 393 errors, when these get fixed we could un-comment code to integrate stylelint into the `sass` task so it fails if there are errors.

**Comment by stewest** [comment]
We'll just need to quickly fix issues, if we want to get rid of all the errors

**Comment by unamaria** [comment]
To make changes to config settings:
- Create PR https://github.com/AmazeeLabs/stylelint-config-amazee

It might be that the sass-specific config used overwrites rules' config. In that case we would need to  check https://github.com/bjankord/stylelint-config-sass-guidelines/blob/master/src/.stylelintrc.json and create a PR in this (d8-starter-composer) repo to extend https://github.com/AmazeeLabs/d8-starter-composer/blob/stylelint/.stylelintrc to overwrite those rules.

**Comment by dan2k3k4** [comment]
@unamaria can this be merged then? 🤔

**Comment by unamaria** [comment]
Merging! Will create another PR to clean up files / fix errors / have stylelint running with gulp. Thanks!

**Pull request merged**
